// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcsympcilspuwupyvapg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jc3ltcGNpbHNwdXd1cHl2YXBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MDY4ODMsImV4cCI6MjA3NjE4Mjg4M30.tt-q4cwI1IAu6m8mh-kdOM4-ZVXadwvI_MIpOVKNsDo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});